### PR TITLE
a binder that can launch different versions of jupyterlab dev builds

### PR DESCRIPTION
**Pull request by tonyfast**
Begin adding `doit` tasks to build a binder. to begin we're gunna steal lots of others have done. 

addresses #18 

https://gke.mybinder.org/v2/gh/deathbeds/accessibility/binder

### CODE REVIEW

**Comment by tonyfast** [comment]
I am pretty sure this binder is working now for testing; at least i'm getting the red bar.

I am not sure the best way to verify it is working.

@bollwyvl could you review some of the targets i commented that went to the build folder. i couldn't set those up correct enough to get doit to work.

**Comment by bollwyvl** [comment]
@goanpeca raised the point of _how the heck do we use this_... we can add a README/CONTRIBUTING update, but didn't want to step on any toes as we're moving forward...

**Comment by isabela-pf** [comment]
I have a draft PR for updating the readme and can add something there if you know what you want. I think @tonyfast could probably also make commits to that PR too since he's in the accessibility organization.

**Comment by tonyfast** [comment]
y'all think we could merge this?

**Review by blink1073 — APPROVED** [review]
Fantastic, I'm excited to see this in action!

**Pull request merged**
