### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by isabela-pf**
Update readme with new info based on current efforts.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
*   Adding link to project and meetings notes?

**Comment by isabela-pf** [comment]
What could this still need? 
- Link to project notes
- Link to project board
- Link to getting started with JLab in general
- Who to reach out to?
-

**Comment by tonyfast** [comment]
[Gitter](https://gitter.im/jupytercalpoly/accessibility)

**Comment by bollwyvl** [comment]
Sooo... we broke it, guess we bought it w/r/t to the binder thing from #20. I _really_ want to get the `pa11y-ci`, GitHub actions, etc. stuff into a PR state, but think we need to take a breath and describe what we actually have merged in now.

Again, to avoid stepping on the toes (eyelashes?) of the "vision" stuff in this PR: as it will get pretty technical pretty quick, perhaps the writeup of `repos.yml`, `dodo.py`, and how to reproduce this whole monstrosity at home, belongs in a dedicated section in a new `CONTRIBUTING.md`? I'll start a PR... once we have _that_ up, then I can build on it to describe how we might add additional tests, etc. Likely I'll use the current specific PRs as a case study, and shift the current `repos.yml` to just be `jupyterlab@3.0.x` and `lumino@master`.

**Comment by tonyfast** [comment]
there still is not module for this repository. are there ways to encode some of these efforts into an API or CLI? or are these things we could automate with the jupyterlab-bot https://github.com/jupyterlab/jupyterlab-bot?

**Comment by isabela-pf** [comment]
Here's the minimum that I think needs to happen with this PR. I think we can do another with more of the good ideas here, but we need the basics now. (I'll update this with the links if you want).

- [ ] Jupyter community calendar link (accessibility meetings listed there)
- [ ] JupyterLab accessibility meetings day and time. I think this could link to the agenda hackmd since that also holds the meeting time and zoom link at the top.
- [ ] The JupyterLab accessibility Github project.

Am I missing any of the basics of what we need so people can join in easily?

@neeniebaby I heard you might have interest in working on some of these manage-y tasks. Would you be interested in making this PR? You can either do it separately and I'll close this one or you can put the PR to my branch and I'm happy to merge it. No pressure, but I wanted to ask in case you were interested 🌻

**Comment by goanpeca** [comment]
@isabela-pf I took the liberty of adding some links

image

**Comment by isabela-pf** [comment]
Thank you so much! I'll leave this open until Monday, March 29 so people have a little more time to add if they want. Then I'll merge and we can always do another PR.

**Comment by neeniebaby** [comment]
I'd be interested in trying it, maybe with a partner?

**Review by willingc — APPROVED** [review]
LGTM. Thanks @isabela-pf. Merging so meeting info is easier to find.

**Comment by isabela-pf** [comment]
> I'd be interested in trying it, maybe with a partner?

@neeniebaby I'm happy to do it with you! Let me know what kind of support you need and I can check in next time I see you.

**Pull request merged**
